### ISSUE TITLE
error TS7016 with "noImplicitAny": true Enabled in tsconfig.json

### ISSUE THREAD

**Issue by SamirJouni** [kubetail-org/fancy-ansi#20]
```
error TS7016: Could not find a declaration file for module 'fancy-ansi'. 'node_modules/fancy-ansi/dist/main.cjs' implicitly has an 'any' type.
Try npm i --save-dev @types/fancy-ansi if it exists or add a new declaration (.d.ts) file containing declare module 'fancy-ansi';
import { FancyAnsi } from 'fancy-ansi';
```

Error persists even with a declaration file like it is done here: https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

**Comment by SamirJouni** [comment]
importing it directly as such solved it: import { FancyAnsi } from '../../node_modules/fancy-ansi/dist/main';

**Comment by amorey** [comment]
What does your tsconfig.json file look like? It might be an issue with the "moduleResolution" setting. Here are two working examples with vite and nextjs that import declaration files correctly:
https://github.com/kubetail-org/fancy-ansi/tree/main/examples/vite-react
https://github.com/kubetail-org/fancy-ansi/tree/main/examples/nextjs
